DNUM-SocialGouv/helios

- .github/workflows/build_lint_tests.yml
Pour avoir plusieurs exemples : https://github.com/vercel/next.js/tree/canary/.github/workflows
> (hel-1) Initialiser la CI

- .husky/prepare-commit-msg
- CONTRIBUTING.md
- README.md
Mise à jour du README
Initie le CONTRIBUTING
Hook de preparation du message de commit (mettre le # de ticket automatiquement)
> hel-11: poser les conventions

- package.json
- yarn.lock
Mise à jour principale pour [Jest 28](https://jestjs.io/docs/upgrading-to-jest28)
> Mise à jour de modules

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/ListItem/ListItem.tsx
- src/frontend/ui/commun/Titre/Titre.tsx
- src/frontend/ui/entité-juridique/PageEntitéJuridique.tsx
- src/frontend/ui/entité-juridique/fiche-d-identité/BlocIdentité.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ListeDesÉtablissementsTerritoriauxRattachés.tsx
- src/frontend/ui/home/Recherche.module.css
- src/frontend/ui/home/Recherche.test.tsx
- src/frontend/ui/home/Recherche.tsx
- src/frontend/ui/établissement-territorial-médico-social/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/BlocIdentitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-sanitaire/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/BlocIdentitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.tsx
- src/pages/recherche.tsx
Bonus : refacto des types pour les props pour être uniforme.
> (hel-133) Afficher le formulaire de recherche

- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.module.css
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/ÉtablissementTerritorialMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/ÉtablissementTerritorialSanitaireViewModel.tsx
il y avait un warning CSS que j'ai corrigé en bonus sur le `end`.
> (hel-175) Correction de l'url vers un EJ quand on est sur un ET

- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialMédicoSocialLoader.ts
- src/backend/métier/entities/établissement-territorial-médico-social/ÉtablissementTerritorialMédicoSocialBudgetEtFinances.ts
- src/backend/test-builder/ÉtablissementTerritorialTestBuilder.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuTauxDeVétustéConstruction.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/ÉtablissementTerritorialMédicoSocialViewModel.tsx
> (hel-241) wip

- .github/workflows/mutation.yml
> (hel-193) Mise en place de la BDD pour la CI du mutation testing

- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuTauxDeVétustéConstruction.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/ÉtablissementTerritorialMédicoSocialAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/ÉtablissementTerritorialSanitaireActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
> Hel 241/afficher taux de vétusté correctifs

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuRésultatNetComptable.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-290) afficher le résultat net comptable

- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuRésultatNetComptable.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
> (hel-290) [WIP] Commit by Thierry on 2022-10-13T10:44:15

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.module.css
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuTauxDeCaf.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-240) wip

- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-239) ne pas afficher de données quand il n'y a pas de données pour le bloc budget et finance

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuFondDeRoulementNetGlobal.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-305) Affiche le fonds de roulement

- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-239) réafficher des indicateurs du bloc budget et finance quand les 3 années sont manquantes

- src/frontend/ui/commun/Bloc/Bloc.module.css
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.module.css
- src/frontend/ui/commun/IndicateurTabulaire/IndicateurTabulaire.tsx
- src/frontend/ui/commun/TableIndicateur/TableIndicateur.module.css
- src/frontend/ui/commun/global.css
- src/frontend/ui/entité-juridique/fiche-d-identité/BlocIdentité.module.css
- src/frontend/ui/entité-juridique/fiche-d-identité/BlocIdentité.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/ÉtablissementTerritorialMédicoSocialAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/BlocIdentitéMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/BlocIdentitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.module.css
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.module.css
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/BlocIdentitéSanitaire.module.css
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/BlocIdentitéSanitaire.tsx
> (hel-310) refacto grille front

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDuNombreDEtpRéalisé.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/ÉtablissementTerritorialMédicoSocialViewModel.tsx
> (hel-253) Afficher le nombre d'ET réalisé

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDuTauxDeRotationDuPersonnel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> (hel-257) Commit by Thierry on 2022-10-25T10:38:40

- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
> (hel-257) Correctifs afficher le taux de rotation du personnel

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialSanitaireViewModelTestBuilder.ts
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/commun/TableIndicateur/TableIndicateur.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/PageÉtablissementTerritorialMédicoSocialActivité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/PageÉtablissementTerritorialMédicoSocialAutorisationEtCapacité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/ÉtablissementTerritorialMédicoSocialAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/ÉtablissementTerritorialMédicoSocialIdentitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/PageÉtablissementTerritorialSanitaireActivité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/ÉtablissementTerritorialSanitaireActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/PageÉtablissementTerritorialSanitaireAutorisationEtCapacité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/ÉtablissementTerritorialSanitaireIdentitéViewModel.tsx
- src/pages/_document.tsx
> (hel-272) refacto du bloc capacite

- database/test-builder/ÉtablissementTerritorialIdentitéModelTestBuilder.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeORMEntitéJuridiqueLoader.test.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeOrmEntitéJuridiqueLoader.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialMédicoSocialLoader.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialRattachéLoader.test.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialRattachéLoader.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialSanitaireLoader.ts
- src/backend/métier/entities/entité-juridique/EntitéJuridique.ts
- src/backend/métier/entities/entité-juridique/ÉtablissementTerritorialRattaché.ts
- src/backend/métier/entities/ÉtablissementTerritorialIdentité.ts
- src/backend/métier/use-cases/RécupèreLesÉtablissementsTerritoriauxRattachésÀLEntitéJuridiqueUseCase.test.ts
- src/backend/test-builder/EntitéJuridiqueTestBuilder.ts
- src/backend/test-builder/ÉtablissementTerritorialTestBuilder.ts
- src/frontend/test-builder/EntitéJuridiqueViewModelTestBuilder.ts
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/test-builder/ÉtablissementTerritorialRattachéViewModelTestBuilder.ts
- src/frontend/test-builder/ÉtablissementTerritorialSanitaireViewModelTestBuilder.ts
- src/frontend/ui/commun/Breadcrumb/Breadcrumb.test.tsx
- src/frontend/ui/entité-juridique/EntitéJuridiqueViewModel.tsx
- src/frontend/ui/entité-juridique/PageEntitéJuridique.test.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ÉtablissementTerritorialRattachéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/PageÉtablissementTerritorialMédicoSocialIdentité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/ÉtablissementTerritorialMédicoSocialIdentitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/ÉtablissementTerritorialMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/PageÉtablissementTerritorialSanitaireIdentité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/ÉtablissementTerritorialSanitaireIdentitéViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/ÉtablissementTerritorialSanitaireViewModel.tsx
> Afficher le libellé court à certains endroits sur EJ et ET

- jest.setup.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.module.css
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/commun/global.css
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDesTauxDAbsentéismes.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> (hel-258) Afficher le taux d'absentéisme

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDuNombreDeCddDeRemplacement.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> (hel-254) Afficher le nombre de CDD de remplacement

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDuTauxDEtpVacants.tsx
- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuDuTauxDePrestationsExternes.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/PageÉtablissementTerritorialMédicoSocialRessourcesHumaines.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> (hel-256) Afficher le taux d'ETP vacants au 31/12

- .github/workflows/helios-ci.yml
- Pipfile
- Pipfile.lock
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
> Passage à python 3.10.8 (ci & scalingo)

- .husky/pre-commit
- database/test-builder/DateMiseÀJourFichierSourceModelTestBuilder.ts
- database/test-builder/ÉtablissementTerritorialAutorisationModelTestBuilder.ts
- download_data_source/infrastructure/gateways/entité-juridique-helios-repository/TypeOrmEntitéJuridiqueHeliosRepository.test.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialMédicoSocialLoader.test.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialSanitaireLoader.test.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialSanitaireLoader.ts
- src/backend/métier/entities/établissement-territorial-sanitaire/ÉtablissementTerritorialSanitaireAutorisation.ts
- src/backend/test-builder/EntitéJuridiqueTestBuilder.ts
- src/backend/test-builder/ÉtablissementTerritorialTestBuilder.ts
- src/frontend/test-builder/ÉtablissementTerritorialSanitaireViewModelTestBuilder.ts
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/PageÉtablissementTerritorialSanitaireAutorisationEtCapacité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
> (hel-335) Ajout liste de capacité pour établissement sanitaire

- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/commun/StringFormater.ts
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/GraphiqueCapacitésParActivité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/GraphiqueCapacitésParActivité.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/PageÉtablissementTerritorialSanitaireAutorisationEtCapacité.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
> (hel-375) Ajouter la mise en exergue à la capacité

- datacrawler/exploration-des-données/entite_juridique/tag_public_prive.ipynb
- download_data_source/infrastructure/gateways/download-raw-data/FinessSftpDownloadRawData.test.ts
- download_data_source/infrastructure/gateways/download-raw-data/FinessSftpDownloadRawData.ts
> (hel-341) Téléchargement fichier nomenclature statuts juridique

- database/dataSource.ts
- database/migrations/1675695881364-AjoutActiviteSanitaireEntiteJuridique.ts
- database/migrations/1675867340170-RenommerColonnePassageUrgenceActivitesEntiteJuridique.ts
> (hel-353) add migrations to rename column activité entité juridique

- src/frontend/ui/commun/Bloc/Bloc.module.css
- src/frontend/ui/commun/Bloc/Bloc.tsx
- src/frontend/ui/entité-juridique/fiche-d-identité/BlocIdentité.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/BlocIdentitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-identité/BlocIdentitéSanitaire.tsx
> Hel 349/ouvrir et fermer les bloc

- src/frontend/ui/entité-juridique/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/entité-juridique/bloc-activité/BlocActivitéSanitare.test.tsx
- src/frontend/ui/entité-juridique/bloc-activité/EntitéJuridiqueActivitésViewModel.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.test.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/InfoBulle/ContenuNombreDeSéjourMCO.tsx
> (hel-342)/ajouter graphique nombre sejours mco ej

- src/frontend/ui/commun/Indicateur/Indicateur.module.css
- src/frontend/ui/commun/Indicateur/Indicateur.tsx
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.module.css
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/ÉtablissementTerritorialMédicoSocialAutorisationsViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsViewModel.tsx
> (hel-425) update css for Details button

- src/frontend/ui/commun/TableIndicateur/TableIndicateur.module.css
- src/frontend/ui/commun/TableIndicateur/TableIndicateur.tsx
> Hel 425/transcription print

- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
> (hel-425) remove separateur

- datacrawler/exploration-des-données/entite_juridique/sejours_had.ipynb
> Hel 351/exploration donnees had

- datacrawler/exploration-des-données/budget_et_finances/QUO_SAN_FINANCE.ipynb
> Hel 398/exploration donnees quo san finance

- src/frontend/ui/commun/Separateur/Separator.module.css
- src/frontend/ui/commun/Separateur/SeparatorVertical.tsx
- src/pages/_app.tsx
> remove css

- Pipfile
- Pipfile.lock
- datacrawler/exploration-des-données/budget_et_finances/QUO_SAN_FINANCE.ipynb
- datacrawler/transform/transforme_le_bloc_ressources_humaines_des_établissements_médico_sociaux/transforme_les_données_des_ressources_humaines_test.py
- package.json
- yarn.lock
> (hel-452) update sentry sdk

- Pipfile
- Pipfile.lock
> update linter version

- .github/workflows/helios-ci.yml
- src/frontend/configuration/frontDependencies.ts
- src/frontend/test-helpers/testHelper.tsx
- src/frontend/ui/commun/contexts/useDependencies.tsx
- src/frontend/ui/entité-juridique/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/utils/featureToggle.test.ts
- src/frontend/utils/featureToggle.ts
> Hel bsr/mecanisme feature toggle

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Graphique/DeuxHistogrammesHorizontaux.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/compte-de-resultat/CompteDeResultat.test.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/compte-de-resultat/CompteDeResultat.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/PageÉtablissementTerritorialMédicoSocialBudgetEtFinances.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/GraphiqueCompteDeResultat.tsx
> Hel 401/refacto composant deux histogrammes

- src/frontend/ui/commun/Graphique/DeuxHistogrammesHorizontaux.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
> (hel-427) Afficher rouge pour les erreurs

- src/frontend/ui/commun/Header/Header.test.tsx
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/utils/featureToggle.ts
> (hel-436) remove deconnection button

- src/frontend/ui/home/Cartographie/Cartographie.tsx
- src/frontend/ui/home/PageRecherche.test.tsx
> (hel-431) ajouter cartographie texte

- src/frontend/configuration/frontDependencies.ts
- src/frontend/ui/commun/contexts/useDependencies.tsx
> fix breadcrumbs with UseEffects

- database/dataSource.ts
- database/migrations/1680014929754-AjouteHAD.ts
- database/models/ActivitéSanitaireEntitéJuridiqueModel.ts
- database/models/ActivitéSanitaireModel.ts
- database/test-builder/ÉtablissementTerritorialActivitéModelTestBuilder.ts
- datacrawler/acceptance_tests/activité_sanitaire_test.py
- datacrawler/acceptance_tests/agrégation_activité_sanitaire_test.py
- datacrawler/extract/lecteur_csv_test.py
- datacrawler/test_helpers/helios_builder.py
- datacrawler/transform/transforme_les_activités_des_établissements_sanitaires/transforme_les_données_men_pmsi_annuel_test.py
- datacrawler/transform/équivalences_diamant_helios.py
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeORMEntitéJuridiqueLoader.test.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeOrmEntitéJuridiqueLoader.ts
- src/backend/métier/entities/entité-juridique/EntitéJuridiqueActivités.ts
> (hel-415) ajoute HAD pour EJ

- database/dataSource.ts
- database/models/CapacitesSanitaireEntiteJuridiqueModel.ts
- database/test-builder/EntitéJuridiqueModelTestBuilder.ts
- database/test-builder/ÉtablissementTerritorialAutorisationModelTestBuilder.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeORMEntitéJuridiqueLoader.test.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeOrmEntitéJuridiqueLoader.ts
- src/backend/métier/entities/entité-juridique/EntitéJuridique.ts
- src/backend/métier/entities/entité-juridique/EntitéJuridiqueAutorisationEtCapacité.ts
- src/backend/métier/gateways/EntitéJuridiqueLoader.ts
- src/backend/métier/use-cases/RécupèreLEntitéJuridiqueUseCase.test.ts
- src/backend/métier/use-cases/RécupèreLEntitéJuridiqueUseCase.ts
- src/backend/testHelper.ts
- src/frontend/test-helpers/test-builder/EntitéJuridiqueViewModelTestBuilder.ts
> Hel 440/transmettre activites ej

- src/frontend/ui/commun/Graphique/DeuxHistogrammesHorizontaux.tsx
- src/frontend/ui/commun/Graphique/SelectionAnnee.tsx
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/compte-de-resultat/CompteDeResultat.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivité.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivitéViewModel.ts
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/GraphiqueCompteDeResultat.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> Hel 444/extraire liste annees

- src/frontend/ui/commun/Graphique/DeuxHistogrammesHorizontaux.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivité.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivitéViewModel.ts
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
> (hel-444) document histogramme data

- src/frontend/ui/eco-conception/PageEcoConception.tsx
> (hel-482) change list pour ordered list

- src/frontend/ui/eco-conception/PageEcoConception.tsx
> (hel-428) change formatting de texte

- src/frontend/ui/eco-conception/PageEcoConception.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOViewModel.tsx
> revert numbered list to paragraph

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivité.tsx
> Hel 444/capacites sanitaire titre

- src/frontend/ui/eco-conception/PageEcoConception.tsx
- src/frontend/ui/gestion-de-cookies/PageGestionDeCookies.tsx
> (hel-433) change le couleur de liens

- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
> (hel-471) mis a jour css pour mettre compte de resultat sur une ligne

- src/frontend/ui/commun/Graphique/GraphiqueViewModel.tsx
- src/frontend/ui/commun/Graphique/HistogrammeVertical.tsx
- src/frontend/ui/commun/Graphique/HistogrammeVerticalABandes.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOViewModel.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/GraphiquePsySSR.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/NombreDeJourneesPsySSRViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
> Hel 404/refact ratio dependance financiere

- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/AutorisationsTagMultiNiveaux.tsx
> (hel-404) fix open close

- src/backend/infrastructure/gateways/entité-juridique-loader/TypeORMEntitéJuridiqueLoader.test.ts
- src/backend/infrastructure/gateways/entité-juridique-loader/TypeOrmEntitéJuridiqueLoader.ts
- src/backend/métier/entities/entité-juridique/AutorisationActivitesFactory.ts
- src/backend/métier/entities/entité-juridique/EntitéJuridiqueAutorisationEtCapacité.ts
- src/backend/métier/use-cases/RécupèreLEntitéJuridiqueUseCase.test.ts
- src/backend/métier/use-cases/RécupèreLEntitéJuridiqueUseCase.ts
- src/frontend/test-helpers/test-builder/EntitéJuridiqueViewModelTestBuilder.ts
- src/frontend/ui/entité-juridique/EntitéJuridiqueViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.test.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/EntitéJuridiqueAutorisationsCapacitesViewModel.tsx
- src/frontend/ui/indicateur-métier/autorisations-activites/GraphiqueAutorisationsActivites.test.tsx
- src/frontend/ui/indicateur-métier/autres-activites/GraphiqueAutresActivites.test.tsx
- src/frontend/ui/indicateur-métier/reconnaissance-contractuelles/GraphiqueReconnaissanceContractuelles.test.tsx
- src/frontend/ui/indicateur-métier/reconnaissance-contractuelles/GraphiqueReconnaissanceContractuelles.tsx
- src/frontend/ui/établissement-territorial-sanitaire/InfoBulle/ContenuReconnaissancesContractuelles.tsx
> Hel 449/ajoute reconnaisance contractuelles

- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/taux-de-caf/TauxDeCaf.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/taux-de-caf/TauxDeCafViewModel.tsx
> (hel-405) extract test taux de caf

- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/AutorisationsTagMultiNiveaux.module.css
- src/frontend/ui/indicateur-métier/taux-de-caf/TauxDeCafViewModel.tsx
> changer taille de le font pour EJ autorisations

- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.test.tsx
> Hel 161/harmoniser mise en exergue

- src/frontend/ui/accessibilite/PageAccessibilite.tsx
- src/pages/accessibilite.tsx
> (hel-434) accessibility

- src/frontend/ui/commun/Graphique/HistogrammesHorizontaux.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/AutorisationsTagMultiNiveaux.module.css
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/AutorisationsTagMultiNiveaux.tsx
- src/frontend/ui/home/Cartographie/Cartographie.module.css
- src/frontend/ui/home/Cartographie/Cartographie.tsx
> (hel-475) retours le front

- src/frontend/ui/commun/Graphique/HistogrammeVerticalABandes.tsx
> (hel-161) désactiver la transcription graphique MCO

- cron.json
- download_data_source/infrastructure/dependencies.ts
> Change cron

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/mot-passe-oublie/FormulaireMdpOublie.tsx
> (hel-510) change wording back to connexion button

- database/models/UtilisateurModel.ts
- src/backend/infrastructure/gateways/forget-password-loader/TypeOrmForgetPasswordLoader.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> (hel-513) allow majus and minus emails

- src/frontend/ui/commun/Header/Header.test.tsx
- src/frontend/ui/commun/Header/Header.tsx
- src/pages/api/auth/[...nextauth].ts
- src/types/next-auth.d.ts
> (hel-514) add firstname to header

- src/backend/infrastructure/gateways/forget-password-loader/TypeOrmForgetPasswordLoader.ts
> (hel-520) correct email wording

- src/frontend/ui/change-mot-passe/useChangeMdp.ts
- src/frontend/ui/commun/Spinner/Spinner.module.css
- src/frontend/ui/commun/Spinner/Spinner.tsx
- src/pages/api/check-token.ts
- src/pages/change-mot-passe.tsx
> (hel-512) url expires within 72 hours

- src/pages/_app.tsx
> (hel-515) force reload when clicking on browser arrow back button

- src/frontend/ui/commun/Graphique/LegendPlugin.ts
- src/frontend/ui/commun/StringFormater.ts
> Hel 502/bug calcul donut

- src/backend/infrastructure/gateways/forget-password-loader/TypeOrmForgetPasswordLoader.ts
> (hel-525) change reinitialisation email wording

- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.test.tsx
> (hel-547) change profile page wording

- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/ÉtablissementTerritorialBudgetEtFinancesMédicoSocialViewModel.tsx
> (hel-544) fix bug indicator bloc budget

- src/frontend/ui/commun/Graphique/Donut.tsx
- src/frontend/ui/commun/Graphique/LegendPluginDonut.ts
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.test.tsx
> (hel-531) seperate the donut legend plugin and the bar legend plugin

- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/registration/RegistrationForm.tsx
> (hel-545) fix inscription rules

- src/backend/infrastructure/controllers/logoutEndpoint.ts
- src/frontend/ui/commun/Header/Header.tsx
- src/pages/api/utilisateurs/logout.ts
> (hel-552) flush cache at logout

- src/frontend/configuration/wording/WordingFr.tsx
- src/pages/api/utilisateurs/createAccount.ts
> (hel-541) change wording

- src/backend/profileFiltersHelper.ts
> (hel-540) correct filter to show category

- src/frontend/ui/commun/Graphique/HistogrammeHorizontaux.module.css
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.module.css
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/BlocBudgetFinance.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.module.css
> Hel 535/pdf layout

- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/frontend/ui/commun/Header/Header.tsx
> (hel-537) make admin page reachable for role 1 and role 2

- src/backend/infrastructure/controllers/logoutEndpoint.ts
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/ÉtablissementTerritorialRessourcesHumainesMédicoSocialViewModel.tsx
- src/pages/api/utilisateurs/logout.ts
> Hel 552/profile not correct

- src/frontend/configuration/wording/WordingFr.tsx
> (hel-554) fix wording

- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/EntitéJuridiqueAutorisationsCapacitesViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/ÉtablissementTerritorialSanitaireAutorisationsCapacitesViewModel.tsx
> Hel 557/wording et san indicateur autorisation

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/home/Cartographie/GroupeBoutonRegions.tsx
> Hel 568/respect accessibility

- package.json
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/change-mot-passe/FormulaireCreatePwd.tsx
- src/frontend/ui/change-mot-passe/PageCreatePwd.tsx
- src/frontend/ui/change-mot-passe/useReinitialisationMdp.ts
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/commun/contexts/userContext.ts
- src/frontend/ui/commun/contexts/userContextProvider.tsx
- src/frontend/ui/login/FormulaireDeConnexion.tsx
- src/pages/creation-mot-passe.tsx
> Hel 561/create pwd page

- package.json
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/commun/Header/Header.tsx
> Hel 564/settings page available only for national admins

- package.json
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/mot-passe-oublie/FormulaireMdpOublie.tsx
> Hel 562/forgot pwd message

- src/frontend/configuration/Paths.ts
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/login/FormulaireDeConnexion.tsx
> (hel-575) delete search bar from create pwd page

- download_data_source/infrastructure/gateways/établissement-territorial-source-externe-loader/FinessXmlÉtablissementTerritorialSourceExterneLoader.ts
> (hel-579) fix data access for drom com

- src/backend/infrastructure/controllers/checkUserIsNotAdminAndInactifEndpoints.ts
- src/backend/infrastructure/controllers/updateLastConnectionDateEndpoints.ts
- src/backend/infrastructure/gateways/change-password-loader/TypeOrmChangePasswordLoader.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/backend/métier/gateways/UtilisateurLoader.ts
- src/backend/métier/use-cases/LoginUseCase.ts
- src/frontend/ui/login/Connexion.module.css
- src/frontend/ui/login/FormulaireDeConnexion.tsx
- src/frontend/ui/parametrage-utilisateurs/EditUser/EditUser.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/ConfirmDeleteModal/ConfirmDeleteModal.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/Filter/AdvancedFilter/AdvancedFilter.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/ItemsPerPage/ItemsPerPage.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/PaginationBtn/PaginationBtn.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/TheadTable/TheadTable.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Reactivate/Reactivate.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/UsersListPage.tsx
- src/frontend/ui/registration/Registration.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.test.tsx
- src/pages/api/utilisateurs/checkUserIsNotAdminAndInactif.ts
- src/pages/api/utilisateurs/updateLastConnectionDate.ts
> Hel 537/page admin

- database/migrations/1701782042926-AjouterSoftDeleteUtilisateur.ts
- database/models/UtilisateurModel.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> Remove soft delete from table user

- database/migrations/1701782042926-AjouterSoftDeleteUtilisateur.ts
- database/models/UtilisateurModel.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> Hel 537/remove soft delete user

- database/dataSource.ts
- database/migrations/1704467337579-RemoveDuplicatedEmailAndMakeItUnique.ts
- database/models/UtilisateurModel.ts
- src/frontend/ui/registration/RegistrationForm.tsx
> Hel 581/creation de compte 2 comptes pour un seul utilisateur adresse mail

- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> consolle admin : hide not connected users

- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivitéViewModel.ts
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
> (hel-583) sort years

- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
> (Hel-584) positive values for compte de resultat using math abs

- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
> (hel-585) positive values for compte resultat errd ca indicateurs

- package.json
- src/frontend/configuration/wording/WordingFr.tsx
> (hel-582) fix wording

- database/dataSource.ts
- database/migrations/1706794831872-ModificationDesValeursDuChampRole.ts
> HEL-593/Console_Administration-Modification_des_valeurs_du_champ_role

- src/frontend/ui/commun/Footer/Footer.test.tsx
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/cookies/Cookies.tsx
- src/pages/_app.tsx
> HEL-571/fix_pb_link)

- src/frontend/ui/parametrage-utilisateurs/EditUser/EditUser.tsx
> HEL-586/bloquer_pour_admin_RR_le_passage_d_un_utilisateur_en_admin_Nat

- src/frontend/ui/commun/Footer/Footer.tsx
> HEL-571 : fix pb

- src/frontend/ui/parametrage-utilisateurs/EditUser/EditUser.tsx
- src/pages/api/utilisateurs/delete.ts
- src/pages/api/utilisateurs/reactivate.ts
- src/pages/api/utilisateurs/update.ts
> Hel 586/v2

- src/frontend/ui/cookies/Cookies.tsx
> fix wordring

- database/migrations/1712743083892-AjoutTableInspectionsControles.ts
- database/models/DateMiseÀJourFichierSourceModel.ts
- database/models/InspectionsModel.ts
- datacrawler/transform/transform_les_donnees_inspections/transforme_les_donnees_inspections.py
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialMédicoSocialLoader.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialSanitaireLoader.ts
- src/backend/métier/entities/ÉtablissementTerritorialQualite.ts
- src/backend/profileFiltersHelper.ts
- src/backend/test-builder/ÉtablissementTerritorialTestBuilder.ts
- src/frontend/test-helpers/test-builder/ÉtablissementTerritorialMédicoSocialViewModelTestBuilder.ts
- src/frontend/test-helpers/test-builder/ÉtablissementTerritorialSanitaireViewModelTestBuilder.ts
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/PageÉtablissementTerritorialMédicoSocialActivité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.test.tsx
> (hel-313) ws recuperation des donnees inspections et controles

- src/frontend/ui/home/Establishment.tsx
- src/frontend/ui/home/Recherche.module.css
> Hel 548/retour resultats recherches 2

- datacrawler/check_downloaded_sivss_file.py
- download_data_source/infrastructure/utils/sirecSourceExternalLoaderUtils.ts
- src/frontend/ui/indicateur-métier/qualite/GraphiqueReclamations.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/evenements-indesirables/GraphiqueEvenementsIndesirables.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.tsx
> (hel-609) affichage historique bloc qualite

- datacrawler/transform/transforme_les_autorisations_et_capacités_des_établissements_médico_sociaux/transforme_les_données_d_autorisation_et_capacité.py
- datacrawler/transform/équivalences_finess_helios.py
> (hel-612) fitlrer les autorisations supprimees

- datacrawler/extract/extrais_la_date_du_nom_de_fichier.py
- datacrawler/extract/trouve_le_nom_du_fichier.py
> fix fichier sirec nommation

- datacrawler/extract/extrais_la_date_du_nom_de_fichier.py
- datacrawler/extract/trouve_le_nom_du_fichier.py
- datacrawler/transform/entite_juridique/budget_finance/transforme_les_donnees_budget_finance_entite_juridique.py
> Rectifier nommage fichiers qualite

- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.test.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/__snapshots__/DetailsAllocations.test.tsx.snap
- src/frontend/ui/indicateur-métier/qualite/ReclamationsParAnnee/HistogrammeHorizontalRowMultiple/HistogrammeHorizontalRowMultiple.test.tsx
- src/frontend/ui/indicateur-métier/qualite/ReclamationsParAnnee/HistogrammeHorizontalRowMultiple/HistogrammeHorizontalRowMultiple.tsx
> HEL-409/Afficher_le_donuts_de_l_allocation_de_ressource_v4 tests

- download_data_source/infrastructure/gateways/download-raw-data/DnumSftpDownloadRawData.ts
> (hel-366) telechargement fichier men pmsi mencumu

- src/frontend/ui/commun/Header/Header.tsx
> (hel-448) fix search from header

- src/frontend/ui/entité-juridique/bloc-budget-finance/AllocationRessourcesViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.tsx
- src/frontend/ui/indicateur-métier/qualite/ReclamationsParAnnee/HistogrammeHorizontalRowMultiple/HistogrammeHorizontalRowMultiple.tsx
> HEL-409/allocation_ressources fix pb

- src/frontend/configuration/wording/WordingFr.tsx
> (hel-628) renommer le bloc autorisation et capacite

- src/frontend/ui/commun/Graphique/SelectionAnneeTag.module.css
- src/frontend/ui/commun/Graphique/SelectionAnneeTags.tsx
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/AllocationRessourcesViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivité.test.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivitéViewModel.ts
- src/frontend/ui/indicateur-métier/qualite/GraphiqueReclamations.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/compte-de-resultat/CompteDeResultatViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/ÉtablissementTerritorialQualiteMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/ÉtablissementTerritorialQualiteSanitaireViewModel.tsx
> Hel 631/indicateurs avec graphe passage liste deroulante a pastilles des annees

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Bloc/Bloc.tsx
- src/frontend/ui/commun/IndicateurGraphique/BlocIndicateurVide.tsx
- src/frontend/ui/commun/toggelMultipleBlocs/ToggelMultipleBlocs.module.css
- src/frontend/ui/commun/toggelMultipleBlocs/ToggelMultipleBlocs.test.tsx
- src/frontend/ui/commun/toggelMultipleBlocs/ToggelMultipleBlocs.tsx
- src/frontend/ui/commun/toggelMultipleBlocs/useToggelMultipleBlocs.ts
- src/frontend/ui/entité-juridique/PageEntitéJuridique.tsx
- src/frontend/ui/entité-juridique/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/entité-juridique/bloc-autorisations-capacites/BlocAutorisationsCapacites.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/BlocBudgetFinance.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.tsx
> HEL-620/Affichage_plie-depliedes_blocs

- database/dataSource.ts
- database/migrations/1720186540616-AjoutRoleAdministrationCentrale.ts
- database/migrations/1720187617872-AjoutInstitutionAdministrationCentrale.ts
- database/migrations/1720428140655-AjoutOrdreRole.ts
- database/models/RoleModel.ts
- src/backend/infrastructure/gateways/role-loader/TypeOrmRoleLoader.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/ExportExcel/ExportExcel.test.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/UsersListPage.tsx
- src/frontend/ui/profile/ProfilePage.tsx
> HEL-580/ajout_du_role-administration_centrale

- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialRattachéLoader.test.ts
- src/backend/infrastructure/gateways/établissement-territorial-loader/TypeOrmÉtablissementTerritorialRattachéLoader.ts
- src/backend/métier/entities/entité-juridique/ÉtablissementTerritorialRattaché.ts
- src/backend/métier/use-cases/RécupèreLesÉtablissementsTerritoriauxRattachésÀLEntitéJuridiqueUseCase.test.ts
- src/frontend/test-helpers/test-builder/EtablissementsTerritoriauxRattachésTestBuilder.ts
- src/frontend/ui/entité-juridique/liste-des-établissements/EtablissementsTerritoriauxRattachésViewModel.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ListeDesÉtablissementsTerritoriauxRattachés.test.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ÉtablissementTerritorialRattachéViewModel.tsx
> HEL-629/fiche_identite-trier_les_etablissements

- datacrawler/check_downloaded_siicea_file.py
- datacrawler/check_downloaded_sivss_file.py
- datacrawler/extract/extrais_la_date_du_nom_de_fichier.py
- datacrawler/extract/trouve_le_nom_du_fichier.py
- datacrawler/import_evenements_indesirables.py
- datacrawler/import_inspections.py
- datacrawler/import_reclamations.py
> fix qualite files manipulation

- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/parametrage-profil/ParametrageProfilPage.tsx
- src/frontend/ui/registration/RegistrationForm.tsx
- src/pages/api/utilisateurs/createAccount.ts
> Hel 580/admin centrale

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Graphique/DonutNoCenterText.tsx
- src/frontend/ui/commun/Graphique/LegendPluginDonutNoCenterText.ts
- src/frontend/ui/entité-juridique/bloc-budget-finance/AllocationRessourcesViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.module.css
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.tsx
> Hel 409/fix retours recette

- datacrawler/check_downloaded_siicea_file.py
- datacrawler/check_downloaded_sivss_file.py
- datacrawler/extract/extrais_la_date_du_nom_de_fichier.py
- datacrawler/extract/trouve_le_nom_du_fichier.py
- datacrawler/import_evenements_indesirables.py
- datacrawler/import_inspections.py
- datacrawler/import_reclamations.py
> Fix master qualite files manipulation

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/inspections-controles/card-inspection-controle/CardInspectionControle.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/ÉtablissementTerritorialQualiteMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/ÉtablissementTerritorialQualiteSanitaireViewModel.tsx
> version 1.1.15

- src/backend/profileFiltersHelper.ts
> (hel-652) fix bug invalid date

- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/PageÉtablissementTerritorialMédicoSocialIdentité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/ÉtablissementTerritorialMédicoSocialIdentitéViewModel.tsx
> (hel-640) acceder fiche ET pricipal

- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Header/Header.module.css
- src/frontend/ui/commun/Header/Header.test.tsx
- src/frontend/ui/commun/Header/Header.tsx
> (hel-638) design menu de compte

- src/frontend/ui/commun/Graphique/DonutNoCenterText.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/AllocationRessourcesViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.test.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/SousEnveloppes/DetailsAllocations.tsx
- src/frontend/ui/indicateur-métier/qualite/ReclamationsParAnnee/HistogrammeHorizontalRowMultiple/HistogrammeHorizontalRowMultiple.test.tsx
- src/frontend/ui/indicateur-métier/qualite/ReclamationsParAnnee/HistogrammeHorizontalRowMultiple/HistogrammeHorizontalRowMultiple.tsx
> Hel 634/affichage dynamique donut allocation ressources

- datacrawler/transform/transforme_les_donnees_allocation_ressource/transforme_les_donnees_allocation_ressource.py
- docker-compose.yaml
- download_data_source/infrastructure/dependencies.ts
- download_data_source/infrastructure/gateways/download-raw-data/ClientFtp.ts
- download_data_source/infrastructure/gateways/download-raw-data/HapiSftpDownloadRawData.ts
- package.json
- src/frontend/ui/établissement-territorial-médico-social/bloc-identité/PageÉtablissementTerritorialMédicoSocialIdentité.test.tsx
- yarn.lock
> (hel-630) fix bug connexion hapi

- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Header/Header.tsx
> (hel-642) modification du message helios

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/change-mot-passe/ChangePwdPage.tsx
- src/frontend/ui/change-mot-passe/FormulaireChangePwd.tsx
- src/frontend/ui/change-mot-passe/changeMdp.module.css
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/commun/Tabs/tabContent.tsx
- src/frontend/ui/commun/Tabs/tabs.tsx
- src/frontend/ui/profile/ProfilePage.tsx
- src/frontend/ui/profile/UserInfoTab.tsx
- src/middleware.ts
- src/pages/mon-compte.tsx
> Hel 618/regrouper les sous menus mon compte et mot de passe

- download_data_source/infrastructure/gateways/download-raw-data/HapiSftpDownloadRawData.ts
> historique 5 ans sur hapi

- src/frontend/ui/change-mot-passe/FormulaireChangePwd.tsx
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/profile/ProfilePage.tsx
- src/frontend/ui/profile/UserInfoTab.tsx
> fix retours weekly

- datacrawler/__init__.py
- datacrawler/import_activites_mensuel.py
- datacrawler/transform/transforme_les_activites_sanitaires_mensuels/transforme_les_donnees_activites_mensuels.py
- datacrawler/transform/équivalences_diamant_helios.py
- src/frontend/ui/commun/Graphique/HistogrammeMensuelFilters.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOHistogrammes.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/NombreDeJournneePsySsrHistogrammes.tsx
> Fix retours cosui

- database/dataSource.ts
- database/migrations/1728314215381-ajoutDeStatutJuridiqueDansLaRecherche.ts
- database/models/RechercheModel.ts
- src/backend/infrastructure/controllers/rechercheAvanceeEndpoint.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/métier/gateways/RechercheLoader.ts
- src/backend/métier/use-cases/RechercheAvanceeParmiLesEntitésEtÉtablissementsUseCase.ts
> (hel-689) ws recherche avancee avec le tri

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
> version 1.1.17

- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/PaginationBtn/PaginationBtn.module.css
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/PaginationBtn/PaginationBtn.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/resultat-recherche-avancee-footer/RechercheAvanceeFooter.module.css
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/resultat-recherche-avancee-footer/RechercheAvanceeFooter.test.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/resultat-recherche-avancee-footer/RechercheAvanceeFooter.tsx
- src/pages/recherche-avancee.tsx
> Hel 693/show lines number table

- src/backend/infrastructure/controllers/rechercheAvanceeEndpoint.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContext.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/recherche-avancee/FiltreStructure.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/RechercheAvanceeFormulaire.module.css
- src/frontend/ui/recherche-avancee/model/Attribues.ts
- src/frontend/ui/recherche-avancee/useRechercheAvancee.ts
- src/pages/api/recherche-avancee.ts
> Hel 688/filtre structure

- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/resultat-recherche-avancee-footer/RechercheAvanceeFooter.tsx
- src/frontend/ui/recherche-avancee/useRechercheAvancee.ts
- src/pages/recherche-avancee.tsx
> hel-697 implémentation de la pagination avec les paramètres dans lurl

- src/backend/infrastructure/controllers/rechercheAvanceeEndpoint.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/métier/gateways/RechercheLoader.ts
- src/backend/métier/use-cases/RechercheAvanceeParmiLesEntitésEtÉtablissementsUseCase.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContext.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/recherche-avancee/FiltreCapacite.tsx
- src/frontend/ui/recherche-avancee/FiltreStructure.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/RechercheAvanceeFormulaire.module.css
- src/frontend/ui/recherche-avancee/model/CapaciteEtablissement.ts
- src/frontend/ui/recherche-avancee/model/ClassificationTypes.ts
- src/frontend/ui/recherche-avancee/useRechercheAvancee.ts
- src/pages/api/recherche-avancee.ts
- src/pages/recherche-avancee.tsx
> Hel 690/filtre capacite

- src/frontend/ui/commun/Tag/SelectionTags.tsx
- src/frontend/ui/commun/Tag/index.tsx
- src/frontend/ui/comparaison/Comparaison.module.css
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/pages/comparaison.tsx
> hel-678 add comparaison page

- package.json
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/commun/Header/Header.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/resultat-recherche-avancee-footer/RechercheAvanceeFooter.tsx
> peparation livraison 25/10/2024

- src/backend/infrastructure/controllers/comparaisonEndpoint.ts
- src/backend/infrastructure/dependencies.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/métier/entities/ResultatDeComparaison.ts
- src/backend/métier/gateways/ComparaisonLoader.ts
- src/backend/métier/use-cases/ComparaisonEtablissementsUseCase.ts
- src/pages/api/comparaison.ts
> Hel 703/ws comparaison

- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> (hel-707) fix date derniere connexion

- src/pages/api/utilisateurs/createAccount.ts
> (hel-708) ajout domaine pour admin centrale

- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/TableHeaderRechercheAvancee.tsx
- src/pages/recherche-avancee.tsx
> Hel 719/retours recherche avancée

- database/dataSource.ts
- database/migrations/1732629322484-AjoutRattachementRecherche.ts
- database/models/RechercheModel.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.test.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/métier/entities/RésultatDeRecherche.ts
- src/backend/métier/use-cases/RechercheParmiLesEntitésEtÉtablissementsUseCase.test.ts
- src/backend/test-builder/RésultatDeRechercheTestBuilder.ts
- src/frontend/ui/commun/Table/Table.module.css
- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/favoris/useFavoris.ts
- src/frontend/ui/home/PageRecherche.test.tsx
- src/frontend/ui/home/RechercheViewModel.tsx
- src/frontend/ui/recherche-avancee/FiltreZoneGeographique.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/RechercheAvanceeFormulaire.module.css
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/useRechercheAvancee.ts
> Hel 663/affichage criteres filtres

- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/frontend/ui/recherche-avancee/FiltreZoneGeographique.tsx
> (hel-657) correction tri zone geographique

- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/recherche-avancee/FiltreStructure.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
> fix query recherche avancee

- src/backend/infrastructure/controllers/comparaisonEndpoint.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.test.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/métier/gateways/ComparaisonLoader.ts
- src/backend/métier/use-cases/ComparaisonEtablissementsUseCase.ts
- src/frontend/ui/comparaison/Comparaison.module.css
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/comparaison/ExportExcel.tsx
- src/pages/api/comparaison/compare.ts
> HEL-679 add export excel comparaison

- src/frontend/ui/recherche-avancee/FiltreZoneGeographique.tsx
> Hel 729/fix filtre zg

- src/backend/infrastructure/controllers/comparaisonEndpoint.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.test.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/métier/entities/ResultatDeComparaison.ts
- src/backend/métier/gateways/ComparaisonLoader.ts
- src/backend/métier/use-cases/ComparaisonEtablissementsUseCase.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Table/Table.module.css
- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/comparaison/ExportExcel.tsx
- src/frontend/ui/comparaison/ajout-etablissements/AjoutEtablissements.tsx
- src/frontend/ui/comparaison/useComparaison.tsx
- src/frontend/ui/home/ComparaisonViewModel.tsx
- src/pages/api/comparaison/compare.ts
- src/pages/comparaison.tsx
> Hel 736/filtre donnees par profil

- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
> Hel 733/affichage etablissements suite recherche

- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.test.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
> (hel-679) fix type capacite

- datacrawler/check_downloaded_siicea_file.py
- datacrawler/check_downloaded_sivss_file.py
- datacrawler/transform/transform_les_donnees_evenements_indesirables_etablissements/transforme_les_donnees_evenements_indesirables_etablissements.py
- datacrawler/transform/transform_les_donnees_inspections/transforme_les_donnees_inspections.py
> (hel-745) fix format date qualite

- database/models/UserListEtablissementModel.ts
- database/models/UserListModel.ts
- src/backend/infrastructure/controllers/userListEndpoint.ts
- src/backend/infrastructure/controllers/userListEtablissementEndpoint.ts
- src/backend/infrastructure/dependencies.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListEtablissementLoader.test.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListEtablissementLoader.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListLoader.test.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListLoader.ts
- src/backend/métier/entities/liste/InformationSurListe.ts
- src/backend/métier/gateways/UserListEtablissementLoader.ts
- src/backend/métier/gateways/UserListLoader.ts
- src/backend/métier/use-cases/userListEtablissementUseCase.ts
- src/backend/métier/use-cases/userListUseCase.ts
- src/backend/testHelper.ts
- src/middleware.ts
- src/pages/api/liste.ts
- src/pages/api/liste/[id].ts
- src/pages/api/liste/[id]/etablissement.ts
- src/pages/api/liste/idAndName.ts
> Hel 739/action backend gestion listes

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/change-mot-passe/FormulaireChangePwd.tsx
- src/frontend/ui/change-mot-passe/FormulaireCreatePwd.tsx
- src/frontend/ui/change-mot-passe/FormulaireReinitialisationMdp.tsx
> (hel-735) HEL-735 update wording error message

- src/pages/liste/[id].tsx
> (hel-668) RG5: Tri des favoris par finess croissant

- src/frontend/ui/favoris/Favoris.module.css
- src/frontend/ui/favoris/FavorisBlock.tsx
- src/frontend/ui/favoris/FavorisPage.tsx
> Hel 667/retours page favoris

- database/migrations/1736865415982-AjoutListEtEtsList.ts
> add favoris to every user

- database/migrations/1736865415982-AjoutListEtEtsList.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
> Fix favoris list migration

- src/frontend/ui/commun/Header/Header.tsx
> Vérification de l’authentification du user avant la recherche de favoris

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
> change version to v1.4.0

- database/models/UserListModel.ts
- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
> Release v1.4.0

- src/backend/infrastructure/controllers/userListEtablissementEndpoint.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListEtablissementLoader.test.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListEtablissementLoader.ts
- src/backend/métier/gateways/UserListEtablissementLoader.ts
- src/backend/métier/use-cases/userListEtablissementUseCase.ts
- src/frontend/ui/commun/StarButtonList/StarButtonList.tsx
- src/frontend/ui/favoris/useFavoris.ts
- src/frontend/ui/liste/ListActionsButton.tsx
- src/pages/api/liste/[id]/etablissement.ts
- src/pages/liste/[id].tsx
> (hel-730) HEL-730 add delete many ets

- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/commun/TuileEtablissement/TuileEtablissement.module.css
- src/frontend/ui/commun/TuileEtablissement/TuileEtablissement.tsx
> Hel 760/affichage logo et texte noir

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/toggelMultipleBlocs/useToggelMultipleBlocs.ts
- src/frontend/ui/entité-juridique/PageEntitéJuridique.tsx
- src/frontend/ui/établissement-territorial-médico-social/PageÉtablissementTerritorialMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.module.css
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/contenu-bloc-rh-vigierh.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.tsx
> Hel 756/affichage des indicateurs vigierh dans helios

- src/frontend/configuration/wording/WordingFr.tsx
> (hel-769) Correction typo dans les messages

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
> Passage en version 1.4.1

- src/frontend/ui/commun/TuileEtablissement/TuileEtablissement.tsx
- src/frontend/ui/entité-juridique/bloc-activité/EntitéJuridiqueActivitésMensuelsViewModel.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOHistogrammes.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/GraphiquePsySSR.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/NombreDeJournneePsySsrHistogrammes.tsx
> Hel 743/date mise a jour activite

- src/backend/infrastructure/controllers/userListEtablissementEndpoint.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListEtablissementLoader.ts
- src/backend/métier/gateways/UserListEtablissementLoader.ts
- src/backend/métier/use-cases/userListEtablissementUseCase.ts
- src/frontend/ui/liste/ExportList.tsx
- src/frontend/ui/liste/ListActionsButton.tsx
- src/frontend/ui/liste/TableauListeEtablissements.tsx
- src/pages/api/liste/[id]/etablissement.ts
- src/pages/liste/[id].tsx
> (hel-721) HEL-721 add export for lists

- src/frontend/ui/commun/Table/Table.tsx
> Fix de la coche de selection

- package.json
- src/frontend/ui/commun/Footer/Footer.tsx
> change version to 1.5.0

- package.json
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Footer/Footer.tsx
- src/frontend/ui/entité-juridique/bloc-activité/EntitéJuridiqueActivitésMensuelsViewModel.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOHistogrammes.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/GraphiquePsySSR.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/NombreDeJournneePsySsrHistogrammes.tsx
- src/frontend/ui/indicateur-métier/qualite/GraphiqueReclamations.tsx
> (hel-771) fix bug affichage des donnees reclamations

- src/frontend/ui/change-mot-passe/ChangePwdPage.tsx
- src/frontend/ui/change-mot-passe/FormulaireChangePwd.tsx
- src/frontend/ui/change-mot-passe/FormulaireCreatePwd.tsx
- src/frontend/ui/change-mot-passe/FormulaireReinitialisationMdp.tsx
- src/frontend/ui/change-mot-passe/PageCreatePwd.tsx
- src/frontend/ui/change-mot-passe/PageReinitialisationMotPasse.tsx
- src/frontend/ui/change-mot-passe/useChangeMdp.ts
- src/frontend/ui/change-mot-passe/useReinitialisationMdp.ts
> (hel-770) HEL-770 add dynamic password message

- src/frontend/ui/home/RésultatsDeRecherche.tsx
> HEL-747 remove number above table

- src/frontend/ui/liste/ListActionsButton.module.css
> (hel-765) HEL-765 fix css for button action

- database/dataSource.ts
- database/models/ÉtablissementTerritorialIdentitéModel.ts
- download_data_source/infrastructure/gateways/download-raw-data/DnumSftpDownloadRawData.test.ts
- download_data_source/infrastructure/gateways/download-raw-data/DnumSftpDownloadRawData.ts
- download_data_source/infrastructure/gateways/download-raw-data/FinessSftpDownloadRawData.test.ts
- download_data_source/infrastructure/gateways/download-raw-data/FinessSftpDownloadRawData.ts
- download_data_source/infrastructure/gateways/download-raw-data/HapiSftpDownloadRawData.ts
> Correction des lint s’affichant dans toutes les PR

- src/backend/infrastructure/controllers/userListEndpoint.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListLoader.ts
- src/backend/métier/gateways/UserListLoader.ts
- src/backend/métier/use-cases/userListUseCase.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/change-mot-passe/FormulaireChangePwd.tsx
- src/frontend/ui/commun/StarButtonList/StarButtonList.module.css
- src/frontend/ui/commun/StarButtonList/StarButtonList.tsx
- src/frontend/ui/favoris/useFavoris.ts
- src/pages/_app.tsx
- src/pages/api/liste.ts
- src/pages/api/liste/[id].ts
> Hel 669/popup creation liste etablissement

- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/comparaison/ExportExcel.tsx
- src/frontend/ui/liste/ListActionsButton.tsx
> (hel-766) HEL-766 add button actions for page comparaison

- src/backend/infrastructure/controllers/comparaisonEndpoint.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.test.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/métier/entities/ParametresDeComparaison.ts
- src/backend/métier/gateways/ComparaisonLoader.ts
- src/backend/métier/use-cases/ComparaisonEtablissementsUseCase.ts
- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/InfoBulle/InfoBulle.tsx
- src/frontend/ui/comparaison/Comparaison.module.css
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/comparaison/ajout-etablissements/AjoutEtablissements.tsx
- src/frontend/ui/comparaison/ajout-etablissements/ListEtablissements.tsx
- src/frontend/ui/comparaison/useComparaison.tsx
- src/pages/api/comparaison/compare.ts
- src/pages/comparaison.tsx
> Hel 782/erreur sentry comparaison vide

- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheAvanceeLoader.test.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.test.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheParNumeroFinessLoader.test.ts
> (hel-772) afficher les resultat plus precis en premier

- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/IndicateursOccupationsEHPAD.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/PageÉtablissementTerritorialMédicoSocialActivité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
> (hel-768) enlever les indicateurs HP HT et AJ des fiches non EHPAD

- src/backend/infrastructure/controllers/rechercheAvanceeEndpoint.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheAvanceeLoader.test.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/métier/entities/ParametresDeRechercheAvancee.ts
- src/backend/métier/gateways/RechercheLoader.ts
- src/backend/métier/use-cases/RechercheAvanceeParmiLesEntitésEtÉtablissementsUseCase.ts
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/liste/ListActionsButton.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ExportExcelRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/TableHeaderRechercheAvancee.tsx
- src/pages/api/recherche-avancee.ts
- src/pages/liste/[id].tsx
- src/pages/recherche-avancee.tsx
> Hel 723/export recherche avancee

- src/backend/profileFiltersHelper.ts
> (hel-651) fix filtre autorisation

- database/dataSource.ts
- database/migrations/1743596937227-ClefEtrangereListEts.ts
- src/backend/infrastructure/gateways/user-list-loader/TypeOrmUserListLoader.ts
- src/frontend/ui/commun/FavorisPopup/FavorisPopup.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
> Hel 669/fix erreur creation list

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/FavorisPopup/FavorisPopup.module.css
- src/frontend/ui/commun/FavorisPopup/FavorisPopup.tsx
- src/frontend/ui/commun/FavorisPopup/useFavorisPopup.ts
- src/frontend/ui/liste/ListActionsButton.tsx
> Hel 669 670 671/changement design popup gestion listes

- src/frontend/ui/commun/FavorisPopup/FavorisPopup.tsx
> Autofocus sur le champs de création de nouvelle liste

- src/frontend/ui/établissement-territorial-médico-social/InfoBulle/ContenuTauxOccupationESMS.tsx
> (hel-791) HEL-791 fix wording for occupation

- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/BlocActivitéMédicoSocial.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/IndicateursOccupationESMS.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/PageÉtablissementTerritorialMédicoSocialActivité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/ÉtablissementTerritorialMédicoSocialActivitéViewModel.tsx
> (hel-790) HEL-790 change order taux occupation non ephad

- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ExportExcelRechercheAvancee.tsx
> Hel 792/export recherche avancee trait union pour fourchettes

- src/frontend/configuration/wording/WordingFr.tsx
> (hel-781) HEL-781 changer wording pour filtre capacite

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/NewFeaturesNotice/NewFeaturesNotice.tsx
- src/frontend/ui/home/PageRecherche.tsx
> Hel 797/message actualite gestion listes

- src/frontend/ui/commun/IndicateurGraphique/BlocIndicateurVide.tsx
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.module.css
- src/frontend/ui/commun/IndicateurGraphique/IndicateurGraphique.tsx
- src/frontend/ui/commun/global.css
- src/frontend/ui/commun/toggelMultipleBlocs/ToggelMultipleBlocs.tsx
- src/frontend/ui/entité-juridique/PageEntitéJuridique.tsx
- src/frontend/ui/entité-juridique/bloc-activité/BlocActivitéSanitaire.tsx
- src/frontend/ui/établissement-territorial-sanitaire/PageÉtablissementTerritorialSanitaire.tsx
> (hel-676) fix telechargement pdf

- src/frontend/ui/recherche-avancee/FiltreCapacite.tsx
- src/frontend/ui/recherche-avancee/FiltreStructure.tsx
- src/frontend/ui/recherche-avancee/FiltreZoneGeographique.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
> Hel 764/accessibilite liens evitement

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/RechercheAvanceeFormulaire.module.css
> Hel 774/renitialiser les champs de la recherche

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/home/TableauEtablissements.tsx
- src/frontend/ui/liste/ListActionsButton.tsx
- src/frontend/ui/liste/TableauListeEtablissements.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/TableHeaderRechercheAvancee.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ToutSelectionnerRechercheAvancee.tsx
- src/pages/liste/[id].tsx
- src/pages/recherche-avancee.tsx
> (hel-789) Revue de la gestion de la selection dans les tableaux

- package.json
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Footer/Footer.tsx
> (hel-814) message actualite

- database/test-builder/EntitéJuridiqueModelTestBuilder.ts
- download_data_source/métier/use-cases/ControleLesDonnesSirecsUseCase.ts
- src/backend/infrastructure/gateways/utilisateur-loader/TypeOrmUtilisateurLoader.ts
- src/frontend/ui/commun/BtnRetourRecherche/BtnRetourRecherche.tsx
- src/frontend/ui/commun/Graphique/Donut.tsx
- src/frontend/ui/commun/Graphique/HistogrammeHorizontalWithToggle.tsx
- src/frontend/ui/commun/Graphique/HistogrammesHorizontaux.tsx
- src/frontend/ui/commun/Header/Header.module.css
- src/frontend/ui/commun/Tabs/tabs.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/comparaison/ajout-etablissements/useRechercheAvanceeComparaison.tsx
- src/frontend/ui/parametrage-profil/ParamatrageTable.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/ExportExcel/ExportExcel.test.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/Pagination/TheadTable/TheadTable.test.tsx
- src/frontend/ui/parametrage-utilisateurs/UsersListPage/UsersListPage.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/ÉtablissementTerritorialQualiteMédicoSocialViewModel.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/ÉtablissementTerritorialQualiteSanitaireViewModel.tsx
> Hel 802/revue reliability sonar

- package.json
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Footer/Footer.tsx
> version 1.6.0.1

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Graphique/HistogrammeHorizontal.tsx
- src/frontend/ui/commun/Graphique/HistogrammeVerticalABandes.tsx
- src/frontend/ui/commun/Graphique/HistogrammesHorizontaux.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/NombreDeSejourMCOHistogrammes.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/NombreDeJournneePsySsrHistogrammes.tsx
- src/frontend/ui/indicateur-métier/nombre-passage-urgence/GraphiqueNombrePassageUrgence.tsx
> Hel 803/adaptation affichage donnee activite

- database/dataSource.ts
- database/migrations/1748332500947-ajoutLaColonneDomaineAuReferentielCategories.ts
- database/models/CategoriesFinessModel.ts
- datacrawler/transform/transforme_les_categories/transforme_les_categories.py
- datacrawler/transform/équivalences_finess_helios.py
- src/frontend/ui/commun/ListeRiche/ListeRiche.tsx
- src/frontend/ui/commun/contexts/ComparaisonContext.ts
- src/frontend/ui/commun/contexts/ComparaisonContextProvider.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContext.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/comparaison/ajout-etablissements/useRechercheAvanceeComparaison.tsx
- src/frontend/ui/recherche-avancee/FiltreCategoriesFiness.tsx
- src/frontend/ui/recherche-avancee/FiltreStructure.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/model/CategoriesFinessViewModel.ts
- src/pages/recherche-avancee.tsx
> Hel 811/dependance entre filtre structure et categories

- LICENSE-EN.TXT
- LICENSE.TXT
> (hel-804) Ajout de la license CeCILL-B

- datacrawler/load/sauvegarde.py
> (hel-283) fix bug suppression python

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/contexts/ComparaisonContext.ts
- src/frontend/ui/commun/contexts/ComparaisonContextProvider.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContext.tsx
- src/frontend/ui/commun/contexts/RechercheAvanceeContextProvider.tsx
- src/frontend/ui/commun/contexts/userContextProvider.tsx
- src/frontend/ui/comparaison/ajout-etablissements/AjoutEtablissements.tsx
- src/frontend/ui/recherche-avancee/FiltreActiviteSanitaire.tsx
- src/frontend/ui/recherche-avancee/RechecheAvanceeFormulaire.tsx
- src/frontend/ui/recherche-avancee/model/ActiviteSanitaire.ts
- src/frontend/ui/recherche-avancee/model/ClassificationTypes.ts
- src/pages/recherche-avancee.tsx
> (hel-682) mettre en place le filtre capacite

- src/frontend/ui/commun/ListeRiche/ListeRiche.tsx
- src/frontend/ui/recherche-avancee/FiltreCategoriesFiness.tsx
> (hel-823) valider le filtre avec la touche entree (in progress)

- src/frontend/ui/recherche-avancee/FiltreActiviteSanitaire.tsx
- src/frontend/ui/recherche-avancee/FiltreCapacite.tsx
> (hel-830) fix wording label values capacite activite

- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/recherche-avancee/FiltreActiviteSanitaire.tsx
- src/frontend/ui/recherche-avancee/FiltreCapacite.tsx
> Hel 830/ajout espace sur les tranches des valeurs

- src/backend/infrastructure/controllers/getTopEnveloppesEndpoint.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/métier/entities/ParametresDeComparaison.ts
- src/backend/métier/entities/ResultatDeComparaison.ts
- src/backend/métier/gateways/ComparaisonLoader.ts
- src/backend/métier/use-cases/ComparaisonEtablissementsUseCase.ts
- src/frontend/ui/commun/Table/Table.tsx
- src/frontend/ui/comparaison/ComparaisonPage.tsx
- src/frontend/ui/comparaison/useComparaison.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/EntitéJuridiqueBudgetFinanceViewModel.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/ratio-dependance-financiere/RatioDependanceFinanciere.tsx
- src/frontend/ui/home/ComparaisonViewModel.tsx
- src/pages/api/comparaison/compare.ts
- src/pages/api/comparaison/getListAnnees.ts
- src/pages/api/comparaison/getTopEnveloppes.ts
> Hel 828/comparaison v2 ej

- src/frontend/ui/indicateur-métier/nombre-de-had/ContenuNombreHAD.tsx
> (hel-842) fix wording detalis indicateur sejours had

- database/dataSource.ts
- database/migrations/1754309418981-AjoutLibelleCategorieALaRecherche.ts
- database/models/RechercheModel.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.test.ts
- src/backend/infrastructure/gateways/comparaison-loader/TypeOrmComparaisonLoader.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.test.ts
- src/backend/infrastructure/gateways/recherche-loader/TypeOrmRechercheLoader.ts
- src/backend/métier/entities/ResultatDeComparaison.ts
- src/backend/métier/entities/RésultatDeRecherche.ts
- src/backend/métier/use-cases/RechercheParmiLesEntitésEtÉtablissementsUseCase.test.ts
- src/backend/test-builder/RésultatDeRechercheTestBuilder.ts
- src/frontend/ui/comparaison/useComparaison.tsx
- src/frontend/ui/favoris/useFavoris.ts
- src/frontend/ui/home/ComparaisonViewModel.tsx
- src/frontend/ui/home/PageRecherche.test.tsx
- src/frontend/ui/home/RechercheViewModel.tsx
- src/frontend/ui/recherche-avancee/resultat-recherche-avancee/ResultatRechercheAvancee.tsx
> Hel 821/ajout colonne categorie dans les tableaux recherche et comparaison

- src/frontend/ui/comparaison/useComparaison.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/AllocationRessources.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/allocation-ressources/ContenuAllocationRessourcesEJ.tsx
> (hel-863) modification wording detail allocation ressources

- src/frontend/ui/comparaison/useComparaison.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/GraphiquePsySSR.tsx
- src/frontend/ui/établissement-territorial-sanitaire/InfoBulle/ContenuNombreDeJournéesPSYetSSR.tsx
- src/frontend/ui/établissement-territorial-sanitaire/InfoBulle/ContenuNombreDeSéjourMCO.tsx
> (hel-874) ajout de precision dans les details de tableau de comparaison

- src/frontend/ui/comparaison/ajout-etablissements/AjoutEtablissements.tsx
- src/frontend/ui/comparaison/ajout-etablissements/ListEtablissements.tsx
> (hel-871) fix ajout etablissements via liste et recherche

- src/frontend/configuration/wording/Wording.tsx
- src/frontend/configuration/wording/WordingFr.tsx
- src/frontend/ui/commun/Titre/Titre.tsx
- src/frontend/ui/entité-juridique/ExportExcelETRattaches.tsx
- src/frontend/ui/entité-juridique/PageEntitéJuridique.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/EtablissementsTerritoriauxRattachésViewModel.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ListeDesÉtablissementsTerritoriauxRattachés.tsx
- src/frontend/ui/entité-juridique/liste-des-établissements/ÉtablissementTerritorialRattachéViewModel.tsx
- src/frontend/ui/etablissement/ActionsButton.tsx
> Hel 876/export et page ej

- datacrawler/ajoute_les_autorisations_des_établissements_médico_sociaux.py
- datacrawler/ajoute_les_autorisations_des_établissements_sanitaires.py
- datacrawler/extract/lecteur_xml.py
- datacrawler/extract/lecteur_xml_test.py
- datacrawler/import_les_entites_juridiques.py
- datacrawler/import_les_etablissements_territoriaux.py
- datacrawler/import_ref_categories.py
- datacrawler/transform/entite_juridique/bloc_identite/transforme_les_donnees_entite_juridique.py
- datacrawler/transform/équivalences_finess_helios.py
- pyproject.toml
> Hel 875/revue lecture xml batch

- src/frontend/test-helpers/GraphiqueTest.tsx
- src/frontend/ui/commun/InfoBulle/InfoBulle.tsx
- src/frontend/ui/commun/Transcription/Transcription.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/compte-de-resultat/CompteDeResultat.test.tsx
- src/frontend/ui/entité-juridique/bloc-budget-finance/ratio-dependance-financiere/RatioDependanceFinanciere.test.tsx
- src/frontend/ui/entité-juridique/bloc-ressources-humaines/BlocRessourcesHumainesEntiteJuridique.test.tsx
- src/frontend/ui/indicateur-métier/capacites-sanitaire-par-activites/GraphiqueCapacitésParActivité.test.tsx
- src/frontend/ui/indicateur-métier/nombre-de-had/GraphiqueNombreHAD.test.tsx
- src/frontend/ui/indicateur-métier/nombre-de-sejour-mco/GraphiqueNombreDeSejourMCO.test.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-psy-ssr/GraphiquePsySSR.test.tsx
- src/frontend/ui/indicateur-métier/nombre-journees-usld/GraphiqueNombreDeJourneesUsld.test.tsx
- src/frontend/ui/indicateur-métier/nombre-passage-urgence/GraphiqueNombrePassageUrgence.test.tsx
- src/frontend/ui/indicateur-métier/resultat-net-comptable/ResultatNetComptable.test.tsx
- src/frontend/ui/indicateur-métier/taux-de-caf/TauxDeCaf.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-activité/PageÉtablissementTerritorialMédicoSocialActivité.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-autorisations/BlocAutorisationEtCapacitéMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-budget-et-finances/BlocBudgetEtFinancesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-qualite/BlocQualite.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/BlocRessourcesHumainesMédicoSocial.test.tsx
- src/frontend/ui/établissement-territorial-médico-social/bloc-ressources-humaines/bloc-vigie-rh/BlocVigieRh.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-activité/BlocActivitéSanitaire.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-autorisations/BlocAutorisationEtCapacitéSanitaire.test.tsx
- src/frontend/ui/établissement-territorial-sanitaire/bloc-qualite/BlocQualite.test.tsx
> fix popup issues
